In [1]:
import numpy as np 
import pandas as pd                           # import libraries


In [9]:
dataset={"Country":["France","Spain","Germany","Spain","France", "Germany","Spain","England"],
         "Age":[ 33,44,66,22,34,65,78,56  ],
        "Salary":[72000,48000,54000,61000,67000,58000 ,83000,67000],
        "Purchased":["Yes","No","Yes","No","Yes","No","Yes","No"]}                # create a dataset
dataset

{'Country': ['France',
  'Spain',
  'Germany',
  'Spain',
  'France',
  'Germany',
  'Spain',
  'England'],
 'Age': [33, 44, 66, 22, 34, 65, 78, 56],
 'Salary': [72000, 48000, 54000, 61000, 67000, 58000, 83000, 67000],
 'Purchased': ['Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No']}

In [10]:
df=pd.DataFrame(dataset)                  #dataset convert  into dataframe
df

Country  Age  Salary Purchased
0   France   33   72000       Yes
1    Spain   44   48000        No
2  Germany   66   54000       Yes
3    Spain   22   61000        No
4   France   34   67000       Yes
5  Germany   65   58000        No
6    Spain   78   83000       Yes
7  England   56   67000        No

In [12]:
# x+y=z        # x and y is independent and z is dependent variable

In [13]:
# country ,age and salary is independent variable and purchased is dependent variable

In [14]:
x=df[["Country","Age","Salary"]]         # x is our independent variable
x

Country  Age  Salary
0   France   33   72000
1    Spain   44   48000
2  Germany   66   54000
3    Spain   22   61000
4   France   34   67000
5  Germany   65   58000
6    Spain   78   83000
7  England   56   67000

In [15]:
x=df[["Country","Age","Salary"]].values        # to make an array
x

array([['France', 33, 72000],
       ['Spain', 44, 48000],
       ['Germany', 66, 54000],
       ['Spain', 22, 61000],
       ['France', 34, 67000],
       ['Germany', 65, 58000],
       ['Spain', 78, 83000],
       ['England', 56, 67000]], dtype=object)

In [18]:
y=df[["Purchased"]]              # y is our dependent variable
y

Purchased
0       Yes
1        No
2       Yes
3        No
4       Yes
5        No
6       Yes
7        No

In [20]:
y=df[["Purchased"]].values        # to make an array
y

array([['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No']], dtype=object)

In [22]:
 from sklearn.impute import SimpleImputer

In [26]:
Imputer=SimpleImputer(missing_values=np.NaN,strategy='mean')        # replace none value to mean values of the columns
Imputer

SimpleImputer()

In [35]:
Imputer=Imputer.fit(x[:,1:3])                   #give the addresss where the value is fit or fill
Imputer

SimpleImputer()

In [37]:
x[:,1:3]=Imputer.transform(x[:,1:3])                      # transfoam the values with mean value

In [38]:
x[:,1:3]

array([[33.0, 72000.0],
       [44.0, 48000.0],
       [66.0, 54000.0],
       [22.0, 61000.0],
       [34.0, 67000.0],
       [65.0, 58000.0],
       [78.0, 83000.0],
       [56.0, 67000.0]], dtype=object)

In [40]:
# categorical data     --> like Country and Purchased
# convert categorical data into numeric data

In [42]:
from sklearn.preprocessing import LabelEncoder     # import labelEncoder library to convert the categorical data to numeric data 

In [43]:
label_encoder_x=LabelEncoder()                 # make object

In [59]:
x[:,0]=label_encoder_x.fit_transform (x[:,0])                  # convert country to numerical data
x[:,0] 

array([0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [46]:
label_encoder_y=LabelEncoder()             # make object

In [58]:
y=label_encoder_y.fit_transform (y[:,0])                   # convert Purchased to numerical data
y

array([1, 0, 1, 0, 1, 0, 1, 0])

In [49]:
# dummy Encoding               -->0,1 


In [50]:
from sklearn.preprocessing import OneHotEncoder          # import module for dummp encoder 

In [51]:
onehotencoder=OneHotEncoder()                  # make object

In [57]:
x=onehotencoder.fit_transform(df.Country.values.reshape(-1,1)).toarray()                   # convert our numerical data into machine lang/dummy encoder
x

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [61]:
#  train test our machine
from sklearn.model_selection import train_test_split

In [93]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=True)

In [94]:
x_train

array([0, 0, 0, 0, 0, 0], dtype=int64)

In [95]:
x_test

array([1, 0], dtype=int64)

In [96]:
y_train

array([0, 1, 1, 1, 0, 0])

In [97]:
y_test

array([0, 1])

In [98]:
# feature Scaling

In [99]:
from sklearn.preprocessing import StandardScaler

In [100]:
sc_x=StandardScaler()

In [101]:
x_train=sc_x.fit_transform(x_train.reshape(-1,1)) 

In [102]:
x_test=sc_x.fit_transform(x_test.reshape(-1,1)) 

In [103]:
x_train

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [104]:
x_test

array([[ 1.],
       [-1.]])